name: Deploy
on:
  release:
    types: [published]
jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ steps.get_token.outputs.app_token }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1
      - name: Export
        run: npm run export
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: ${{ steps.get_token.outputs.app_token }}
          branch: gh-pages # The branch the action should deploy to.
          folder: out # The folder the action should deploy.
          force: true # Force-push new deployments to overwrite the previous version.
          clean: true # JamesIves/github-pages-deploy-action@v4.3.3
          clean-exclude: |
            .nojekyll
            .gitignore
